[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "llama-cpp-python>=0.3.34",
    "nvidia-cublas-cu12>=12.9.2.10",
    "nvidia-cudnn-cu12>=9.24.0.43",
    "openwakeword>=0.4.0",
    "piper-tts>=1.6.0",
    "sentence-transformers>=5.7.0",
    "silero-vad>=6.2.1",
]

[project.scripts]
jarvis = "jarvis:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
